<a href="https://colab.research.google.com/github/Karuneshtiwari/ML-lab/blob/main/Lab03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial.distance import minkowski

from google.colab import drive
drive.mount('/content/drive')

DATA_FILE = "/content/drive/MyDrive/ML_lab/Lab Session Data.xlsx"


def load_dataset(file_path):
    """
    Load the marketing_campaign sheet from the Excel file.
    """
    return pd.read_excel(file_path, sheet_name="marketing_campaign")

dataset = load_dataset(DATA_FILE)

print("Dataset Loaded Successfully!")
print("Shape :", dataset.shape)

display(dataset.head())

Mounted at /content/drive
Dataset Loaded Successfully!
Shape : (2240, 29)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,2012-04-09 00:00:00,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,2014-08-03 00:00:00,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,2014-10-02 00:00:00,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

In [2]:
# A1 : Identify Feature Datatypes

def identify_feature_types(dataframe):

    feature_information = []

    for column in dataframe.columns:

        dtype = dataframe[column].dtype

        if dtype == "object":
            measurement = "Nominal"

        elif "date" in column.lower() or "dt_" in column.lower():
            measurement = "Interval"

        elif dataframe[column].nunique() <= 15:
            measurement = "Ordinal"

        else:
            measurement = "Ratio"

        feature_information.append({

            "Feature": column,
            "Python Datatype": str(dtype),
            "Measurement Type": measurement

        })

    return pd.DataFrame(feature_information)

In [3]:
# MAIN PROGRAM

# A1
print("=" * 70)
print("A1 : IDENTIFY FEATURE DATATYPES")
print("=" * 70)

feature_information = identify_feature_types(dataset)

display(feature_information)

======================================================================
A1 : IDENTIFY FEATURE DATATYPES
======================================================================

                Feature Python Datatype Measurement Type
0                    ID           int64            Ratio
1            Year_Birth           int64            Ratio
2             Education          object          Nominal
3        Marital_Status          object          Nominal
4                Income         float64            Ratio
5               Kidhome           int64          Ordinal
6              Teenhome           int64          Ordinal
7           Dt_Customer          object          Nominal
8               Recency           int64            Ratio
9              MntWines           int64            Ratio
10            MntFruits           int64            Ratio
11      MntMeatProducts           int64            Ratio
12      MntFishProducts           int64            Ratio
13     MntSweetProducts           int64            Ratio
14         MntGoldProds           int64            Ratio
15    NumDealsPurchases           int64          Ordinal
16      NumWebPurchases           int64          Ordinal
17  NumCatalogPurchases           int64          Ordinal
18    NumStorePurchases           int64          Ordinal
19    NumWebVisitsMonth           int64            Ratio
20         AcceptedCmp3           int64          Ordinal
21         AcceptedCmp4           int64          Ordinal
22         AcceptedCmp5           int64          Ordinal
23         AcceptedCmp1           int64          Ordinal
24         AcceptedCmp2           int64          Ordinal
25             Complain           int64          Ordinal
26        Z_CostContact           int64          Ordinal
27            Z_Revenue           int64          Ordinal
28             Response           int64          Ordinal